---
title: "Data Screening MGCFA"
author: "Erin M. Buchanan"
date: "9/23/2019"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup_datascreen, include=FALSE}
# chunk options 
knitr::opts_chunk$set(echo = FALSE, include = FALSE, 
                      cache = TRUE, message = FALSE, warning = FALSE)

## Seed for random number generation
set.seed(37563)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)

# Libraries 
library(mice)
library(dplyr)

# Percent missing function
percentmiss <- function(x){ sum(is.na(x))/length(x) *100 }

# Data Screening Function
## Be sure to put ID column as column 1, source as 2
datascreen <- function(df) {
  
  # Missing Data
  missing <- apply(df, 1, percentmiss)
  ## Rows
  replace_rows <- df[missing <= 5, ]
  dont_replace_rows <- df[missing > 5, ]
  ## Columns
  missing <- apply(replace_rows, 2, percentmiss)
  replace_columns <- replace_rows[ , missing <= 5]
  dont_replace_columns <- cbind(replace_rows[ , 1:2] , replace_rows[ , missing > 5])
  replace_columns <- replace_columns[ , -c(1,2)]
  ## Replacement
  tempnomiss <- mice(replace_columns)
  miced_columns <- complete(tempnomiss, 1)
  all_columns <- cbind(dont_replace_columns, miced_columns)
  ## Put back in the original order
  all_columns <- all_columns[ , colnames(df)] 
  nomiss <- rbind(all_columns, dont_replace_rows)
  ## How many points
  points_estimated <- sum(tempnomiss$where)
  
  # Outliers
  mahal <- mahalanobis(nomiss[ , -c(1:2)],
                       colMeans(nomiss[ , -c(1:2)], na.rm = T),
                       cov(nomiss[ , -c(1:2)], use = "pairwise.complete.obs"))
  cutoff <- qchisq(1-.001, ncol(nomiss[ , -c(1:2)]))
  outliers <- sum(mahal > cutoff, na.rm = T)
  
  # Assumptions
  ## Prep
  random_compare <- rchisq(nrow(nomiss), 7)
  fake <- lm(random_compare ~ ., data = nomiss[ ,-c(1:2)])
  standardized <- rstudent(fake)
  fitted <- scale(fake$fitted.values)

  ## Additivity - in return
  ## Linearity
  qqnorm(standardized); abline(0,1)
  line_plot <- recordPlot()

  ## Normality
  hist(standardized)
  hist_plot <- recordPlot()

  ## Homog + S
  plot(fitted, standardized); abline(0,0); abline(v = 0)
  homogs_plot <- recordPlot()
  
  nomiss$outliers <- mahal
  
  return(list(fulldata = nomiss,
              missing_points = points_estimated,
              num_outliers = outliers,
              correl = summary(fake, correlation = T)$correl, 
              linearity = line_plot,
              normality = hist_plot,
              homogen = homogs_plot))
}

# Import overall file
alldata <- read.csv("all_data_combined_edit.csv")
alldata <- subset(alldata,
                  source != "paper")
alldata$source <- droplevels(alldata$source)

# Build a place to put the stuff
summary_ds <- data.frame(scale_name = character(0),
                         sample_size = numeric(),
                         missing_points = numeric(),
                         number_outliers = numeric(),
                         correl = numeric(),
                         linear = character(0),
                         normal = character(0), 
                         homogeneity = character(0),
                         homoscedasticity = character(0),
                         stringsAsFactors = F)
```

```{r ds_boredom_proneness}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
bp_df <- alldata[ , grepl("partno|source|BP[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
bp_df <- bp_df %>% 
  select(partno, source, everything())

# Reverse Code
## In the qualtrics true = 1, false = 2
## Reverse code the false ones
## False (1): 1, 7, 8, 11, 13, 15, 18, 22, 23, 24 
## True (1): 2, 3, 4, 5, 6, 9, 10, 12, 14, 16, 17, 19, 20, 21, 25, 26, 27, 28
## Plus 2 for the first two columns
bp_df[ , c(1, 7, 8, 11, 13, 15, 18, 22, 23, 24)+2] <- 3 - bp_df[ , c(1, 7, 8, 11, 13, 15, 18, 22, 23, 24)+2] 
## Now change from 2 = false to 0 = false
bp_df[ , -c(1,2)] <- 2 - bp_df[ , -c(1,2)]

# Data Screening
bp_ds <- datascreen(bp_df)

# Make some decisions, save your answers, comment these out
# Note I had to copy this to the console for this to work
# bp_ds$linearity
# bp_ds$normality
# bp_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("BP", sum(!is.na(bp_ds$fulldata$outliers)),
                      # missing points, number outliers
                      bp_ds$missing_points, bp_ds$num_outliers, 
                      # additivity
                      sum(abs(bp_ds$correl) > .90 & abs(bp_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "Yes", "Yes")
```

```{r ds_boredom_proneness_sf}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
bpsf_df <- alldata[ , grepl("partno|source|BPSF[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
bpsf_df <- bpsf_df %>% 
  select(partno, source, everything())

# Reverse Code
## No reverse coded items. 

# Data Screening
bpsf_ds <- datascreen(bpsf_df)

# Make some decisions, save your answers, comment these out
# bpsf_ds$linearity
# bpsf_ds$normality
# bpsf_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("BPSF", sum(!is.na(bpsf_df$fulldata$outliers)),
                      # missing points, number outliers
                      bpsf_ds$missing_points, bpsf_ds$num_outliers, 
                      # additivity
                      sum(abs(bpsf_ds$correl) > .90 & abs(bpsf_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "No", "Yes", "Yes")
```

```{r ds_brief_resilience_scale}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
brs_df <- alldata[ , grepl("partno|source|BRS[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
brs_df <- brs_df %>% 
  select(partno, source, everything())

# Reverse Code
## 1 to 5 scale with items 2, 4, 6 reversed
brs_df[ , c(2,4,6)+2] <- 6 - brs_df[ , c(2,4,6)+2]

# Data Screening
brs_ds <- datascreen(brs_df)

# Make some decisions, save your answers, comment these out
# brs_ds$linearity
# brs_ds$normality
# brs_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("BRS", sum(!is.na(brs_df$fulldata$outliers)),
                      # missing points, number outliers
                      brs_ds$missing_points, brs_ds$num_outliers, 
                      # additivity
                      sum(abs(brs_ds$correl) > .90 & abs(brs_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "No", "No", "No", "No")
```

```{r ds_dms}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
dms_df <- alldata[ , grepl("partno|source|DMSTEXT[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
dms_df <- dms_df %>% 
  select(partno, source, everything())

# Reverse Code
## No reverse coding 

# Data Screening
## Deal with text columns
dms_df$DMSTEXT8 <- as.numeric(as.character(dms_df$DMSTEXT8))
dms_df$DMSTEXT11 <- as.numeric(as.character(dms_df$DMSTEXT11))
dms_df$DMSTEXT13 <- as.numeric(as.character(dms_df$DMSTEXT13))
dms_ds <- datascreen(dms_df)

# Make some decisions, save your answers, comment these out
# dms_ds$linearity
# dms_ds$normality
# dms_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("DMS", sum(!is.na(dms_df$fulldata$outliers)),
                      # missing points, number outliers
                      dms_ds$missing_points, dms_ds$num_outliers, 
                      # additivity
                      sum(abs(dms_ds$correl) > .90 & abs(dms_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "No", "Yes")
```

```{r ds_elm}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
elm_df <- alldata[ , grepl("partno|source|ELM[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
elm_df <- elm_df %>% 
  select(partno, source, everything())

# Reverse Code
## No reverse coding 

# Data Screening
## Deal with text columns
elm_ds <- datascreen(elm_df)

# Make some decisions, save your answers, comment these out
# elm_ds$linearity
# elm_ds$normality
# elm_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("ELM", sum(!is.na(elm_df$fulldata$outliers)),
                      # missing points, number outliers
                      elm_ds$missing_points, elm_ds$num_outliers, 
                      # additivity
                      sum(abs(elm_ds$correl) > .90 & abs(elm_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "Yes", "No")
```

```{r ds_elq}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
elq_df <- alldata[ , grepl("partno|source|ELQ[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
elq_df <- elq_df %>% 
  select(partno, source, everything())

# Reverse Code
## Reverse items 2, 7, 14, 18
elq_df[ , c(2, 7, 14, 18)+2] <- 6 - elq_df[ , c(2, 7, 14, 18)+2]

# Data Screening
## Deal with text columns
elq_ds <- datascreen(elq_df)

# Make some decisions, save your answers, comment these out
# elq_ds$linearity
# elq_ds$normality
# elq_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("ELQ", sum(!is.na(elq_df$fulldata$outliers)),
                      # missing points, number outliers
                      elq_ds$missing_points, elq_ds$num_outliers, 
                      # additivity
                      sum(abs(elq_ds$correl) > .90 & abs(elq_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "Yes", "Yes")
```

```{r ds_emas}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
emas_df <- alldata[ , grepl("partno|source|EMAS[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
emas_df <- emas_df %>% 
  select(partno, source, everything())

# Reverse Code
## No reverse coded items

# Data Screening
## Deal with text columns
emas_ds <- datascreen(emas_df)

# Make some decisions, save your answers, comment these out
# emas_ds$linearity
# emas_ds$normality
# emas_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("EMAS", sum(!is.na(emas_df$fulldata$outliers)),
                      # missing points, number outliers
                      emas_ds$missing_points, emas_ds$num_outliers, 
                      # additivity
                      sum(abs(emas_ds$correl) > .90 & abs(emas_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "Yes", "Yes")
```

```{r ds_ems}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
ems_df <- alldata[ , grepl("partno|source|EMS[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
ems_df <- ems_df %>% 
  select(partno, source, everything())

# Reverse Code
## Reverse Code. 1, 4, 7, 8, 9, 10, 13, 17, 19
## The paper says that seven of them were reverse coded but doesn't say which
## These items definitely are reversed given the histograms
ems_df[ , c(1, 4, 7:10, 13, 17, 19)+2] <- 6 - ems_df[ , c(1, 4, 7:10, 13, 17, 19)+2] 

# Data Screening
## Deal with text columns
ems_ds <- datascreen(ems_df)

# Make some decisions, save your answers, comment these out
# ems_ds$linearity
# ems_ds$normality
# ems_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("EMS", sum(!is.na(ems_df$fulldata$outliers)),
                      # missing points, number outliers
                      ems_ds$missing_points, ems_ds$num_outliers, 
                      # additivity
                      sum(abs(ems_ds$correl) > .90 & abs(ems_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "No", "Yes")
```

```{r ds_es}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
es_df <- alldata[ , grepl("partno|source|ES[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
es_df <- es_df %>% 
  select(partno, source, everything())

# Reverse Code
## Reverse Code. 2, 15, 21, 26, 36
es_df[ , c(2, 15, 21, 26, 36)+2] <- 7 - es_df[ , c(2, 15, 21, 26, 36)+2] 

# Data Screening
## Deal with text columns
es_ds <- datascreen(es_df)

# Make some decisions, save your answers, comment these out
# es_ds$linearity
# es_ds$normality
# es_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("ES", sum(!is.na(es_df$fulldata$outliers)),
                      # missing points, number outliers
                      es_ds$missing_points, es_ds$num_outliers, 
                      # additivity
                      sum(abs(es_ds$correl) > .90 & abs(es_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "No", "No", "No")
```

```{r ds_fom}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
fom_df <- alldata[ , grepl("partno|source|FOM[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
fom_df <- fom_df %>% 
  select(partno, source, everything())

# Reverse Code
## Fix qualtrics coding that's incorrect 1-5 instead of 0-4
fom_df[ , c(1:12)+2] <- fom_df[ , c(1:12)+2] - 1

##Reverse Code. 2, 4, 5, 7, 9 , 11
fom_df[ , c(2, 4, 5, 7, 9, 11)+2] <- 4 - fom_df[ , c(2, 4, 5, 7, 9, 11)+2] 

# Data Screening
## Deal with text columns
fom_ds <- datascreen(fom_df)

# Make some decisions, save your answers, comment thfome out
# fom_ds$linearity
# fom_ds$normality
# fom_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("FOM", sum(!is.na(fom_df$fulldata$outliers)),
                      # missing points, number outliers
                      fom_ds$missing_points, fom_ds$num_outliers, 
                      # additivity
                      sum(abs(fom_ds$correl) > .90 & abs(fom_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "Yes", "Yes", "Yes")
```

```{r ds_glps}
# Data
## Expression is partno | (or) put in the letters you want, leave numbers
glps_df <- alldata[ , grepl("partno|source|GLPS[0-9]+", colnames(alldata))]
## Make sure partno and source are at the beginning
glps_df <- glps_df %>% 
  select(partno, source, everything())

# Reverse Code
## Reverse Code 5, 8, 13
glps_df[ , c(5, 8, 13)+2] <-  8 - glps_df[ , c(5, 8, 13)+2]

# Data Screening
## Deal with text columns
glps_ds <- datascreen(glps_df)

# Make some decisions, save your answers, comment thglpse out
# glps_ds$linearity
# glps_ds$normality
# glps_ds$homogen

summary_ds[nrow(summary_ds)+1, ] <- 
                    #scale name, sample size
                    c("GLPS", sum(!is.na(glps_df$fulldata$outliers)),
                      # missing points, number outliers
                      glps_ds$missing_points, glps_ds$num_outliers, 
                      # additivity
                      sum(abs(glps_ds$correl) > .90 & abs(glps_ds$correl) < 1), 
                      # linearity, normality, homog, homos
                      "Yes", "No", "Yes", "No")
```


