---
title: "MGCFA"
author: "Erin M. Buchanan"
date: "9/23/2019"
output: html_document
---

```{r setup_mg, include=FALSE}
# chunk options 
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE, warning = FALSE)

## Seed for random number generation
set.seed(37563)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)

# Libraries 
library(lavaan)
#library(equaltestMI)

summary_mg <- data.frame(scale_name = character(0),
                         scale_size = numeric(),
                         model_step = character(0),
                         sample_size = numeric(),
                         chisq = numeric(),
                         df = numeric(),
                         cfi = numeric(),
                         rmsea = numeric(),
                         srmr = numeric(),
                         diffchisq = numeric(),
                         diffdf = numeric(),
                         ncp = numeric(),
                         chisqp = numeric(), 
                         stringsAsFactors = F)

```

```{r eq_test, include = F}
# Counsell, Cribbie, Flora (2019) Function for Equivalence Tests

#This function conducts an equivalence test based on SEM output
# see manuscript for exact numeric details

# The inputs are:
# significance level (alpha) which is .05 by default, 
# observed chi square statistic (chi), 
# model (or model difference in) degrees of freedom (df) 
# number of groups (m)
# sample size (N_sample)
# the value of the RMSEA that you will set for the equivalence bounds, 
# default is RMSEA = .08

#do not modify anything below

equiv_chi=function(alpha=.05,chi,df,m,N_sample,popRMSEA=.08){
    Fml<-chi/(N_sample-m)
    popep<-(df*popRMSEA^2)/m
    popdelt<-(N_sample-m)*popep
    pval<-pchisq(chi, df, ncp=popdelt, lower.tail=TRUE)   
    res<-data.frame(chi,Fml,popep,popdelt,pval)
    res
}

# Yuan and Chan's (2016) method for getting an adjusted RMSEA value
# from conventional values of .05, .08, or .10.

# The formula is based on the coefficients in Table 11 of Yuan and Chan (2016);
# The inputs are:
# the number of groups (m), 
# sample size (N_sample), 
# degrees of freedom (df)
# conventional value for RMSEA (RMSEA_c): must use .05, .08, or .10

#do not modify anything below

RMSEA_ctoa=function(m,N_sample,df,RMSEA_c){
    RMSEA_a=NULL
    N=N_sample
    if (RMSEA_c ==.05){
        if (m==1){
            n=N-m;
            y_e=2.06034-.62974*log(df)+.02512*log(df)*log(df)-.98388*log(n)+.05442*log(n)*log(n)-.00005188*n+.05260*log(df)*log(n);
        }else if (m==2){
            n=N-m;
            y_e=2.61777-.67451*log(df)+.02596*log(df)*log(df)-.99310*log(n)+.04739*log(n)*log(n)+.05331*log(df)*log(n);
        }else if (m==3){
            n=N-m;
            y_e=2.98724-.67419*log(df)+.02566*log(df)*log(df)-1.03326*log(n)+.04855*log(n)*log(n)+.05022*log(df)*log(n);
        }else if (m==4){
            n=N-m;
            y_e=1.98287-.66535*log(df)+.02518*log(df)*log(df)-.95007*log(n)+.71711*(n**(1/5))+.04695*log(df)*log(n);
        }else if (m==5){
            n=N-m;
            y_e=2.12615-.65419*log(df)+.02468*log(df)*log(df)-.94634*log(n)+.69787*(n**(1/5))+.04390*log(df)*log(n);
        }
    }
    if (RMSEA_c==.08){
        if (m==1){
            n=N-m;
            y_e=2.84129-.54809*log(df)+.02296*log(df)*log(df)-.76005*log(n)+.10229*log(n)*log(n)-1.11167*(n**(1/5))+.04845*log(df)*log(n);
        }else if (m==2){
            n=N-m;
            y_e=3.73383-.61834*log(df)+.02487*log(df)*log(df)-.93229*log(n)+.11073*log(n)*log(n)-1.09715*(n**(1/5))+.05296*log(df)*log(n);
        }else if (m==3){
            n=N-m;
            y_e=2.91386-.65125*log(df)+.02563*log(df)*log(df)-1.09019*log(n)+.06789*log(n)*log(n)-.00948*sqrt(n)+.05430*log(df)*log(n);
        }else if (m==4){
            n=N-m;
            y_e=3.04581-.66589*log(df)+.02588*log(df)*log(df)-1.05019*log(n)+.05572*log(n)*log(n)-.00003864*n+.05406*log(df)*log(n);
        }else if (m==5){
            n=N-m;
            y_e=3.21990-.67182*log(df)+.02591*log(df)*log(df)-1.05668*log(n)+.05430*log(n)*log(n)-.00002718*n+.05314*log(df)*log(n);
        }
    }
    if (RMSEA_c==.10){
        if (m==1){
            n=N-m;
            y_e=2.36352-.49440*log(df)+.02131*log(df)*log(df)-.64445*log(n)+.09043*log(n)*log(n)-1.01634*(n**(1/5))+.04422*log(df)*log(n);
        }else if (m==2){
            n=N-m;
            y_e=3.34834-.56888*log(df)+.02354*log(df)*log(df)-.81593*log(n)+.10506*log(n)*log(n)-1.10591*(n**(1/5))+.04962*log(df)*log(n);
        }else if (m==3){
            n=N-m;
            y_e=3.90933-.61431*log(df)+.02476*log(df)*log(df)-.92236*log(n)+.11054*log(n)*log(n)-1.10284*(n**(1/5))+.05273*log(df)*log(n);
        }else if (m==4){
            n=N-m;
            y_e=2.96570-.63962*log(df)+.02537*log(df)*log(df)-1.07005*log(n)+.06814*log(n)*log(n)-.01029*sqrt(n)+.05396*log(df)*log(n);
        }else if (m==5){
            n=N-m;
            y_e=3.18941-.65440*log(df)+.02568*log(df)*log(df)-1.09231*log(n)+.06714*log(n)*log(n)-.00894*sqrt(n)+.05424*log(df)*log(n);
        }
    } 
    RMSEA_a=exp(y_e);
    result=data.frame(m,N_sample,df,RMSEA_c,RMSEA_a)
    #  return(result);
    #print(result, row.names = FALSE)
}
########################################################################################
```

```{r function_lavaan, include = F}
equal_test <- function(model_input, data_input, rmsea_input){
  
  #overall model
  overall.fit <- cfa(model = model_input,
                       data = data_input, 
                       meanstructure = TRUE)
  
  random <- subset(data_input,
                   source == "random")
  nonrandom <- subset(data_input,
                      source == "not random")
  
  # Individual groups
  random.fit <- cfa(model = model_input,
                    data = random,
                    meanstructure = T)
  
  random.equal <- equiv_chi(alpha = .05,
                            chi = fitMeasures(random.fit, "chisq"),
                            df = fitMeasures(random.fit, "df"),
                            m = 1, 
                            N_sample = random.fit@SampleStats@nobs[[1]], 
                            popRMSEA = rmsea_input)
  
  nonrandom.fit <- cfa(model = model_input,
                    data = nonrandom,
                    meanstructure = T)
  
  nonrandom.equal <- equiv_chi(alpha = .05,
                          chi = fitMeasures(nonrandom.fit, "chisq"),
                          df = fitMeasures(nonrandom.fit, "df"),
                          m = 1, 
                          N_sample = nonrandom.fit@SampleStats@nobs[[1]], 
                          popRMSEA = rmsea_input)

  # Configural
  config.fit <- cfa(model = model_input,
                     data = data_input,
                     group = "source", 
                     meanstructure = T)

  # Metric
  metric.fit <- cfa(model = model_input,
                    data = data_input,
                    group = "source", 
                    meanstructure = T,
                    group.equal = c("loadings"))
  
  metric.equal <- equiv_chi(alpha = .05,
                            chi = abs(fitMeasures(metric.fit, "chisq") - fitMeasures(config.fit, "chisq")),
                            df = abs(fitMeasures(metric.fit, "df") - fitMeasures(config.fit, "df")), 
                            m = 2, 
                            N_sample = sum(unlist(metric.fit@SampleStats@nobs)),
                            popRMSEA = rmsea_input)
  
  # Scalar
  scalar.fit <- cfa(model = model_input,
                    data = data_input,
                    group = "source", 
                    meanstructure = T,
                    group.equal = c("loadings", "intercepts"))
  
  scalar.equal <- equiv_chi(alpha = .05,
                            chi = abs(fitMeasures(scalar.fit, "chisq") - fitMeasures(metric.fit, "chisq")),
                            df = abs(fitMeasures(scalar.fit, "df") - fitMeasures(metric.fit, "df")), 
                            m = 2, 
                            N_sample = sum(unlist(scalar.fit@SampleStats@nobs)),
                            popRMSEA = rmsea_input)
  
  # Strict
  residuals.fit <- cfa(model = model_input,
                    data = data_input,
                    group = "source", 
                    meanstructure = T,
                    group.equal = c("loadings", "intercepts", "residuals"))
  
  residuals.equal <- equiv_chi(alpha = .05,
                            chi = abs(fitMeasures(residuals.fit, "chisq") - fitMeasures(scalar.fit, "chisq")),
                            df = abs(fitMeasures(residuals.fit, "df") - fitMeasures(scalar.fit, "df")), 
                            m = 2, 
                            N_sample = sum(unlist(residuals.fit@SampleStats@nobs)),
                            popRMSEA = rmsea_input)
  
  return(list(overall = overall.fit, 
              random = random.fit, 
              random.equal = random.equal,
              nonrandom = nonrandom.fit, 
              nonrandom.equal = nonrandom.equal, 
              configural = config.fit, 
              metric = metric.fit, 
              metric.equal = metric.equal,
              scalar = scalar.fit, 
              scalar.equal = scalar.equal,
              residuals = residuals.fit, 
              residuals.equal = residuals.equal))
}

```

```{r data_screening, child = '2 datascreening.Rmd'}
```

```{r mg_boredom_proneness, include = F}
# Model Code
overall.model  <- '
BP =~ BP1 + BP2 + BP3 + BP4 + BP5 + BP6 + BP7 + BP8 + 
      BP9 + BP10 + BP11 + BP12 + BP13 + BP14 + BP15 + 
      BP16 + BP17 + BP18 + BP19 + BP20 + BP21 + BP22 + 
      BP23 + BP24 + BP25 + BP26 + BP27 + BP28
'

## models
bp_mg <- equal_test(overall.model, bp_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]), 
    "Overall", bp_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]),
    "Random", bp_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bp_mg$random.equal$chi,
    fitmeasures(bp_mg$random, "df"),
    bp_mg$random.equal$popdelt,
    bp_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]),
    "NonRandom", bp_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bp_mg$nonrandom.equal$chi,
    fitmeasures(bp_mg$nonrandom, "df"),
    bp_mg$nonrandom.equal$popdelt,
    bp_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(bp_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(bp_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bp_mg$metric.equal$chi,
    abs(fitmeasures(bp_mg$metric, "df") - fitmeasures(bp_mg$configural, "df")),
    bp_mg$metric.equal$popdelt,
    bp_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(bp_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bp_mg$scalar.equal$chi,
    abs(fitmeasures(bp_mg$scalar, "df") - fitmeasures(bp_mg$metric, "df")),
    bp_mg$scalar.equal$popdelt,
    bp_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bp_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(bp_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bp_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bp_mg$residuals.equal$chi,
    abs(fitmeasures(bp_mg$residuals, "df") - fitmeasures(bp_mg$scalar, "df")),
    bp_mg$residuals.equal$popdelt,
    bp_mg$residuals.equal$pval)
```

```{r mg_boredom_proneness_shortform, include = F}
# Model Code
overall.model = '
INT =~ BPSF1 + BPSF3 + BPSF5 + BPSF6 + BPSF8 + BPSF9
EXT =~ BPSF2 + BPSF4 + BPSF7 + BPSF10 + BPSF11 + BPSF12
'

## models
bpsf_mg <- equal_test(overall.model, bpsf_df$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]), 
    "Overall", bpsf_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]),
    "Random", bpsf_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bpsf_mg$random.equal$chi,
    fitmeasures(bpsf_mg$random, "df"),
    bpsf_mg$random.equal$popdelt,
    bpsf_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]),
    "NonRandom", bpsf_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bpsf_mg$nonrandom.equal$chi,
    fitmeasures(bpsf_mg$nonrandom, "df"),
    bpsf_mg$nonrandom.equal$popdelt,
    bpsf_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(bpsf_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(bpsf_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bpsf_mg$metric.equal$chi,
    abs(fitmeasures(bpsf_mg$metric, "df") - fitmeasures(bpsf_mg$configural, "df")),
    bpsf_mg$metric.equal$popdelt,
    bpsf_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(bpsf_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bpsf_mg$scalar.equal$chi,
    abs(fitmeasures(bpsf_mg$scalar, "df") - fitmeasures(bpsf_mg$metric, "df")),
    bpsf_mg$scalar.equal$popdelt,
    bpsf_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(bpsf_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(bpsf_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(bpsf_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    bpsf_mg$residuals.equal$chi,
    abs(fitmeasures(bpsf_mg$residuals, "df") - fitmeasures(bpsf_mg$scalar, "df")),
    bpsf_mg$residuals.equal$popdelt,
    bpsf_mg$residuals.equal$pval)
```

```{r mg_briefresiliencescale, include = F}
# Model Code
overall.model = '
BRS =~ BRS1 + BRS2 + BRS3 + BRS4 + BRS5 + BRS6
'

## models
brs_mg <- equal_test(overall.model, brs_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]), 
    "Overall", brs_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]),
    "Random", brs_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    brs_mg$random.equal$chi,
    fitmeasures(brs_mg$random, "df"),
    brs_mg$random.equal$popdelt,
    brs_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]),
    "NonRandom", brs_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    brs_mg$nonrandom.equal$chi,
    fitmeasures(brs_mg$nonrandom, "df"),
    brs_mg$nonrandom.equal$popdelt,
    brs_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(brs_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(brs_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    brs_mg$metric.equal$chi,
    abs(fitmeasures(brs_mg$metric, "df") - fitmeasures(brs_mg$configural, "df")),
    brs_mg$metric.equal$popdelt,
    brs_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(brs_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    brs_mg$scalar.equal$chi,
    abs(fitmeasures(brs_mg$scalar, "df") - fitmeasures(brs_mg$metric, "df")),
    brs_mg$scalar.equal$popdelt,
    brs_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(brs_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(brs_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(brs_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    brs_mg$residuals.equal$chi,
    abs(fitmeasures(brs_mg$residuals, "df") - fitmeasures(brs_mg$scalar, "df")),
    brs_mg$residuals.equal$popdelt,
    brs_mg$residuals.equal$pval)
```

```{r mg_dms, include = F}
# Model Code
overall.model = '
EudaimonicBehaviors =~ DMSTEXT1 + DMSTEXT2 + DMSTEXT3 + DMSTEXT4 + DMSTEXT5 + DMSTEXT6 + DMSTEXT7
HedonicBehaviors =~ DMSTEXT8 + DMSTEXT9 + DMSTEXT10 + DMSTEXT11 + DMSTEXT12 + DMSTEXT13 + DMSTEXT14 +  DMSTEXT15 + DMSTEXT16 + DMSTEXT17 + DMSTEXT18 + DMSTEXT19
'


## models
dms_mg <- equal_test(overall.model, dms_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]), 
    "Overall", dms_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]),
    "Random", dms_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    dms_mg$random.equal$chi,
    fitmeasures(dms_mg$random, "df"),
    dms_mg$random.equal$popdelt,
    dms_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]),
    "NonRandom", dms_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    dms_mg$nonrandom.equal$chi,
    fitmeasures(dms_mg$nonrandom, "df"),
    dms_mg$nonrandom.equal$popdelt,
    dms_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(dms_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(dms_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    dms_mg$metric.equal$chi,
    abs(fitmeasures(dms_mg$metric, "df") - fitmeasures(dms_mg$configural, "df")),
    dms_mg$metric.equal$popdelt,
    dms_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(dms_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    dms_mg$scalar.equal$chi,
    abs(fitmeasures(dms_mg$scalar, "df") - fitmeasures(dms_mg$metric, "df")),
    dms_mg$scalar.equal$popdelt,
    dms_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(dms_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(dms_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(dms_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    dms_mg$residuals.equal$chi,
    abs(fitmeasures(dms_mg$residuals, "df") - fitmeasures(dms_mg$scalar, "df")),
    dms_mg$residuals.equal$popdelt,
    dms_mg$residuals.equal$pval)
```

```{r mg_elm, include = F}
# Model Code
overall.model = '
RS =~ ELM1 + ELM2 + ELM3 + ELM4 + ELM5 + ELM6 + ELM7 + ELM8 +
ELM9 + ELM10 + ELM11 + ELM12 + ELM13 + ELM14 + ELM15 + ELM16 +
ELM17 + ELM18 + ELM19 + ELM20 + ELM21 + ELM22 + ELM23 + ELM24 +
ELM25 + ELM26 + ELM27 + ELM28 + ELM28 + ELM29 + ELM30 + ELM31 +
ELM32 + ELM33 + ELM34 + ELM35 + ELM36 + ELM37 + ELM38 + ELM39 +
ELM40' 

## models
elm_mg <- equal_test(overall.model, elm_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]), 
    "Overall", elm_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]),
    "Random", elm_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elm_mg$random.equal$chi,
    fitmeasures(elm_mg$random, "df"),
    elm_mg$random.equal$popdelt,
    elm_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]),
    "NonRandom", elm_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elm_mg$nonrandom.equal$chi,
    fitmeasures(elm_mg$nonrandom, "df"),
    elm_mg$nonrandom.equal$popdelt,
    elm_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(elm_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(elm_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elm_mg$metric.equal$chi,
    abs(fitmeasures(elm_mg$metric, "df") - fitmeasures(elm_mg$configural, "df")),
    elm_mg$metric.equal$popdelt,
    elm_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(elm_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elm_mg$scalar.equal$chi,
    abs(fitmeasures(elm_mg$scalar, "df") - fitmeasures(elm_mg$metric, "df")),
    elm_mg$scalar.equal$popdelt,
    elm_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elm_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(elm_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elm_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elm_mg$residuals.equal$chi,
    abs(fitmeasures(elm_mg$residuals, "df") - fitmeasures(elm_mg$scalar, "df")),
    elm_mg$residuals.equal$popdelt,
    elm_mg$residuals)
```

```{r mg_elq, include = F}
# Model Code
overall.model = '
ELQ =~ ELQ1 + ELQ2 + ELQ3 + ELQ4 + ELQ5 + ELQ6 + ELQ7 + ELQ8 + ELQ9 + ELQ10 + ELQ11 + ELQ12 + ELQ13 + ELQ14 +
ELQ15 + ELQ16 + ELQ17 + ELQ18 + ELQ19 + ELQ20 + ELQ21
'

## models
elg_mg <- equal_test(overall.model, elq_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]), 
    "Overall", elg_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]),
    "Random", elg_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elg_mg$random.equal$chi,
    fitmeasures(elg_mg$random, "df"),
    elg_mg$random.equal$popdelt,
    elg_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]),
    "NonRandom", elg_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elg_mg$nonrandom.equal$chi,
    fitmeasures(elg_mg$nonrandom, "df"),
    elg_mg$nonrandom.equal$popdelt,
    elg_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(elg_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(elg_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elg_mg$metric.equal$chi,
    abs(fitmeasures(elg_mg$metric, "df") - fitmeasures(elg_mg$configural, "df")),
    elg_mg$metric.equal$popdelt,
    elg_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(elg_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elg_mg$scalar.equal$chi,
    abs(fitmeasures(elg_mg$scalar, "df") - fitmeasures(elg_mg$metric, "df")),
    elg_mg$scalar.equal$popdelt,
    elg_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(elg_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(elg_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(elg_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    elg_mg$residuals.equal$chi,
    abs(fitmeasures(elg_mg$residuals, "df") - fitmeasures(elg_mg$scalar, "df")),
    elg_mg$residuals.equal$popdelt,
    elg_mg$residuals.equal$pval)

```

```{r mg_emas, include = F}
# Model Code
overall.model = '
EMAS =~ EMAS1 + EMAS2 + EMAS3 + EMAS4 + EMAS5 + EMAS6 + EMAS7 + EMAS8 + EMAS9 + EMAS10 + EMAS11 + EMAS12
'

## models
emas_mg <- equal_test(overall.model, emas_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]), 
    "Overall", emas_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]),
    "Random", emas_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    emas_mg$random.equal$chi,
    fitmeasures(emas_mg$random, "df"),
    emas_mg$random.equal$popdelt,
    emas_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]),
    "NonRandom", emas_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    emas_mg$nonrandom.equal$chi,
    fitmeasures(emas_mg$nonrandom, "df"),
    emas_mg$nonrandom.equal$popdelt,
    emas_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(emas_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(emas_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    emas_mg$metric.equal$chi,
    abs(fitmeasures(emas_mg$metric, "df") - fitmeasures(emas_mg$configural, "df")),
    emas_mg$metric.equal$popdelt,
    emas_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(emas_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    emas_mg$scalar.equal$chi,
    abs(fitmeasures(emas_mg$scalar, "df") - fitmeasures(emas_mg$metric, "df")),
    emas_mg$scalar.equal$popdelt,
    emas_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(emas_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(emas_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(emas_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    emas_mg$residuals.equal$chi,
    abs(fitmeasures(emas_mg$residuals, "df") - fitmeasures(emas_mg$scalar, "df")),
    emas_mg$residuals.equal$popdelt,
    emas_mg$residuals.equal$pval)

```

```{r mg_ems, include = F}
# Model Code
overall.model = '
EMS =~ EMS1 + EMS6 + EMS6  + EMS8 + EMS9 + EMS14 + EMS15 + EMS17 + EMS18 + EMS19
'

## models
ems_mg <- equal_test(overall.model, ems_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]), 
    "Overall", ems_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]),
    "Random", ems_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ems_mg$random.equal$chi,
    fitmeasures(ems_mg$random, "df"),
    ems_mg$random.equal$popdelt,
    ems_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]),
    "NonRandom", ems_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ems_mg$nonrandom.equal$chi,
    fitmeasures(ems_mg$nonrandom, "df"),
    ems_mg$nonrandom.equal$popdelt,
    ems_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(ems_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(ems_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ems_mg$metric.equal$chi,
    abs(fitmeasures(ems_mg$metric, "df") - fitmeasures(ems_mg$configural, "df")),
    ems_mg$metric.equal$popdelt,
    ems_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(ems_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ems_mg$scalar.equal$chi,
    abs(fitmeasures(ems_mg$scalar, "df") - fitmeasures(ems_mg$metric, "df")),
    ems_mg$scalar.equal$popdelt,
    ems_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ems_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(ems_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ems_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ems_mg$residuals.equal$chi,
    abs(fitmeasures(ems_mg$residuals, "df") - fitmeasures(ems_mg$scalar, "df")),
    ems_mg$residuals.equal$popdelt,
    ems_mg$residuals.equal$pval)
```

```{r mg_es, include = F}
# Model Code
overallmodel = '
SelfDistance =~ ES3 + ES5 + ES19 + ES32 + ES40 + ES42 + ES43 + ES44
SelfTrans =~ ES2 + ES4 + ES11 + ES12 + ES13 + ES14 + ES21 + ES27 + ES33 + ES34 + ES35 + ES36 + ES41 + ES45
Freedom =~ ES9 + ES10 + ES15 + ES17 + ES18 + ES23 + ES24 + ES26 + ES28 + ES31 + ES46
Responsibility =~ ES1 + ES6 + ES7 + ES8 + ES16 + ES20 + ES22 + ES25 + ES29 + ES30 + ES37 + ES38 + ES39
'

## models
es_mg <- equal_test(overall.model, es_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]), 
    "Overall", es_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]),
    "Random", es_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    es_mg$random.equal$chi,
    fitmeasures(es_mg$random, "df"),
    es_mg$random.equal$popdelt,
    es_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]),
    "NonRandom", es_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    es_mg$nonrandom.equal$chi,
    fitmeasures(es_mg$nonrandom, "df"),
    es_mg$nonrandom.equal$popdelt,
    es_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(es_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(es_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    es_mg$metric.equal$chi,
    abs(fitmeasures(es_mg$metric, "df") - fitmeasures(es_mg$configural, "df")),
    es_mg$metric.equal$popdelt,
    es_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(es_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    es_mg$scalar.equal$chi,
    abs(fitmeasures(es_mg$scalar, "df") - fitmeasures(es_mg$metric, "df")),
    es_mg$scalar.equal$popdelt,
    es_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(es_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(es_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(es_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    es_mg$residuals.equal$chi,
    abs(fitmeasures(es_mg$residuals, "df") - fitmeasures(es_mg$scalar, "df")),
    es_mg$residuals.equal$popdelt,
    es_mg$residuals.equal$pval)

```

```{r mg_fom, include = F}
# Model Code
overall.model = '
FOM =~ FOM1 + FOM2 + FOM3 + FOM4 + FOM5 + FOM6 + FOM7 +
FOM8 + FOM9 + FOM10 + FOM11 + FOM12
'

## models
fom_mg <- equal_test(overall.model, fom_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]), 
    "Overall", fom_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]),
    "Random", fom_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    fom_mg$random.equal$chi,
    fitmeasures(fom_mg$random, "df"),
    fom_mg$random.equal$popdelt,
    fom_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]),
    "NonRandom", fom_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    fom_mg$nonrandom.equal$chi,
    fitmeasures(fom_mg$nonrandom, "df"),
    fom_mg$nonrandom.equal$popdelt,
    fom_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(fom_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(fom_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    fom_mg$metric.equal$chi,
    abs(fitmeasures(fom_mg$metric, "df") - fitmeasures(fom_mg$configural, "df")),
    fom_mg$metric.equal$popdelt,
    fom_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(fom_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    fom_mg$scalar.equal$chi,
    abs(fitmeasures(fom_mg$scalar, "df") - fitmeasures(fom_mg$metric, "df")),
    fom_mg$scalar.equal$popdelt,
    fom_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(fom_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(fom_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(fom_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    fom_mg$residuals.equal$chi,
    abs(fitmeasures(fom_mg$residuals, "df") - fitmeasures(fom_mg$scalar, "df")),
    fom_mg$residuals.equal$popdelt,
    fom_mg$residuals.equal$pval)

```

```{r mg_glps, include = F}
# Model Code
overallmodel = '
GLPS =~ GLPS1 + GLPS2 + GLPS3 + GLPS4 + GLPS5 + GLPS6 + GLPS7
+ GLPS8 + GLPS9 + GLPS10 + GLPS11 + GLPS12 + GLPS13 + GLPS14 + GLPS15
'


## models
glps_mg <- equal_test(overall.model, glps_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]), 
    "Overall", glps_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]),
    "Random", glps_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    glps_mg$random.equal$chi,
    fitmeasures(glps_mg$random, "df"),
    glps_mg$random.equal$popdelt,
    glps_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]),
    "NonRandom", glps_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    glps_mg$nonrandom.equal$chi,
    fitmeasures(glps_mg$nonrandom, "df"),
    glps_mg$nonrandom.equal$popdelt,
    glps_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(glps_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(glps_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    glps_mg$metric.equal$chi,
    abs(fitmeasures(glps_mg$metric, "df") - fitmeasures(glps_mg$configural, "df")),
    glps_mg$metric.equal$popdelt,
    glps_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(glps_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    glps_mg$scalar.equal$chi,
    abs(fitmeasures(glps_mg$scalar, "df") - fitmeasures(glps_mg$metric, "df")),
    glps_mg$scalar.equal$popdelt,
    glps_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(glps_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(glps_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(glps_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    glps_mg$residuals.equal$chi,
    abs(fitmeasures(glps_mg$residuals, "df") - fitmeasures(glps_mg$scalar, "df")),
    glps_mg$residuals.equal$popdelt,
    glps_mg$residuals.equal$pval)

```


```{r mg_fap, include = F}
# Model Code

##this one is missing from data screening - not sure why 

```

```{r mg_lapr, include = F}
# Model Code
overall.model = '
LP =~ LAPR11 + LAPR19 + LAPR20 + LAPR27 + LAPR28 + LAPR35 + LAPR36 + LAPR43
EV =~ LAPR1 + LAPR9 + LAPR13 + LAPR17 + LAPR25 + LAPR31 + LAPR37
LC =~ LAPR14 + LAPR22 + LAPR38
Death =~ LAPR16 +LAPR24 + LAPR32 + LAPR40
WM =~ LAPR4 + LAPR6 + LAPR12 + LAPR33 + LAPR41 + LAPR44 
GS =~ LAPR18 + LAPR21 + LAPR26 + LAPR34 
FMF =~ LAPR_2 + LAPR5 + LAPR10 + LAPR42
'


## models
lapr_mg <- equal_test(overall.model, lapr_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]), 
    "Overall", lapr_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]),
    "Random", lapr_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lapr_mg$random.equal$chi,
    fitmeasures(lapr_mg$random, "df"),
    lapr_mg$random.equal$popdelt,
    lapr_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]),
    "NonRandom", lapr_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lapr_mg$nonrandom.equal$chi,
    fitmeasures(lapr_mg$nonrandom, "df"),
    lapr_mg$nonrandom.equal$popdelt,
    lapr_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(lapr_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(lapr_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lapr_mg$metric.equal$chi,
    abs(fitmeasures(lapr_mg$metric, "df") - fitmeasures(lapr_mg$configural, "df")),
    lapr_mg$metric.equal$popdelt,
    lapr_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(lapr_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lapr_mg$scalar.equal$chi,
    abs(fitmeasures(lapr_mg$scalar, "df") - fitmeasures(lapr_mg$metric, "df")),
    lapr_mg$scalar.equal$popdelt,
    lapr_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lapr_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(lapr_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lapr_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lapr_mg$residuals.equal$chi,
    abs(fitmeasures(lapr_mg$residuals, "df") - fitmeasures(lapr_mg$scalar, "df")),
    lapr_mg$residuals.equal$popdelt,
    lapr_mg$residuals.equal$pval)

```

```{r mg_las, include = F}
# Model Code
overallmodel = '
LAS =~ LAS1 + LAS2 + LAS3 + LAS4 + LAS5 + LAS6 + LAS7 + LAS8 +LAS9 +LAS10 + LAS11 + LAS12 + LAS13 + LAS14 + LAS15 + LAS16 + LAS17 + LAS18 + LAS19 + LAS20 + LAS21 +LAS22 + LAS23 + LAS24 + LAS25 + LAS26 + LAS27
'



## models
las_mg <- equal_test(overall.model, las_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]), 
    "Overall", las_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]),
    "Random", las_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    las_mg$random.equal$chi,
    fitmeasures(las_mg$random, "df"),
    las_mg$random.equal$popdelt,
    las_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]),
    "NonRandom", las_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    las_mg$nonrandom.equal$chi,
    fitmeasures(las_mg$nonrandom, "df"),
    las_mg$nonrandom.equal$popdelt,
    las_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(las_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(las_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    las_mg$metric.equal$chi,
    abs(fitmeasures(las_mg$metric, "df") - fitmeasures(las_mg$configural, "df")),
    las_mg$metric.equal$popdelt,
    las_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(las_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    las_mg$scalar.equal$chi,
    abs(fitmeasures(las_mg$scalar, "df") - fitmeasures(las_mg$metric, "df")),
    las_mg$scalar.equal$popdelt,
    las_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(las_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(las_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(las_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    las_mg$residuals.equal$chi,
    abs(fitmeasures(las_mg$residuals, "df") - fitmeasures(las_mg$scalar, "df")),
    las_mg$residuals.equal$popdelt,
    las_mg$residuals.equal$pval)

```

```{r mg_let, include = F}
# Model Code
overall.model = '
Life =~ LET1 + LET2 + LET3 + LET4 + LET5 + LET6
'


## models
let_mg <- equal_test(overall.model, let_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]), 
    "Overall", let_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]),
    "Random", let_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    let_mg$random.equal$chi,
    fitmeasures(let_mg$random, "df"),
    let_mg$random.equal$popdelt,
    let_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]),
    "NonRandom", let_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    let_mg$nonrandom.equal$chi,
    fitmeasures(let_mg$nonrandom, "df"),
    let_mg$nonrandom.equal$popdelt,
    let_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(let_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(let_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    let_mg$metric.equal$chi,
    abs(fitmeasures(let_mg$metric, "df") - fitmeasures(let_mg$configural, "df")),
    let_mg$metric.equal$popdelt,
    let_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(let_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    let_mg$scalar.equal$chi,
    abs(fitmeasures(let_mg$scalar, "df") - fitmeasures(let_mg$metric, "df")),
    let_mg$scalar.equal$popdelt,
    let_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(let_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(let_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(let_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    let_mg$residuals.equal$chi,
    abs(fitmeasures(let_mg$residuals, "df") - fitmeasures(let_mg$scalar, "df")),
    let_mg$residuals.equal$popdelt,
    let_mg$residuals.equal$pval)

```

```{r mg_lpq, include = F}
# Model Code
overall.model = '
LPQ =~
LPQ1 + LPQ2 + LPQ3 + LPQ4 + LPQ5 + LPQ6 + LPQ7 +
LPQ8 + LPQ9 + LPQ10 + LPQ11 + LPQ12 + LPQ13 + LPQ14 + 
LPQ15 + LPQ16 + LPQ17 + LPQ18 + LPQ19 + LPQ20
'

## models
lpq_mg <- equal_test(overall.model, lpq_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]), 
    "Overall", lpq_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]),
    "Random", lpq_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lpq_mg$random.equal$chi,
    fitmeasures(lpq_mg$random, "df"),
    lpq_mg$random.equal$popdelt,
    lpq_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]),
    "NonRandom", lpq_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lpq_mg$nonrandom.equal$chi,
    fitmeasures(lpq_mg$nonrandom, "df"),
    lpq_mg$nonrandom.equal$popdelt,
    lpq_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(lpq_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(lpq_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lpq_mg$metric.equal$chi,
    abs(fitmeasures(lpq_mg$metric, "df") - fitmeasures(lpq_mg$configural, "df")),
    lpq_mg$metric.equal$popdelt,
    lpq_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(lpq_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lpq_mg$scalar.equal$chi,
    abs(fitmeasures(lpq_mg$scalar, "df") - fitmeasures(lpq_mg$metric, "df")),
    lpq_mg$scalar.equal$popdelt,
    lpq_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lpq_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(lpq_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lpq_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lpq_mg$residuals.equal$chi,
    abs(fitmeasures(lpq_mg$residuals, "df") - fitmeasures(lpq_mg$scalar, "df")),
    lpq_mg$residuals.equal$popdelt,
    lpq_mg$residuals.equal$pval)

```

```{r mg_lri, include = F}
# Model Code
overall.model = '
FRAME =~ LRI1 + LRI3 + LRI4 + LRI7 + LRI8 + LRI9 + LRI10 + LRI11 + LRI13 + LRI14 + LRI16 + LRI23 + LRI25 + LRI28
FULFILL =~ LRI2 + LRI5 + LRI6 + LRI12 + LRI15 + LRI17 + LRI18 + LRI19 + LRI20 + LRI21 + LRI22 + LRI24 + LRI26 + LRI27'


## models
lri_mg <- equal_test(overall.model, lri_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]), 
    "Overall", lri_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]),
    "Random", lri_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lri_mg$random.equal$chi,
    fitmeasures(lri_mg$random, "df"),
    lri_mg$random.equal$popdelt,
    lri_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]),
    "NonRandom", lri_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lri_mg$nonrandom.equal$chi,
    fitmeasures(lri_mg$nonrandom, "df"),
    lri_mg$nonrandom.equal$popdelt,
    lri_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(lri_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(lri_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lri_mg$metric.equal$chi,
    abs(fitmeasures(lri_mg$metric, "df") - fitmeasures(lri_mg$configural, "df")),
    lri_mg$metric.equal$popdelt,
    lri_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(lri_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lri_mg$scalar.equal$chi,
    abs(fitmeasures(lri_mg$scalar, "df") - fitmeasures(lri_mg$metric, "df")),
    lri_mg$scalar.equal$popdelt,
    lri_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(lri_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(lri_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(lri_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    lri_mg$residuals.equal$chi,
    abs(fitmeasures(lri_mg$residuals, "df") - fitmeasures(lri_mg$scalar, "df")),
    lri_mg$residuals.equal$popdelt,
    lri_mg$residuals.equal$pval)

```

```{r mg_mapa, include = F}
# Model Code
overall.model = '
MAPA =~ MAPA1 + MAPA2 + MAPA3 + MAPA4 + MAPA5 + MAPA6 + MAPA7 + MAPA8 + MAPA9 + MAPA10
+ MAPA11 + MAPA12 + MAPA13 + MAPA14 + MAPA15 + MAPA16 + MAPA17 + MAPA18 + MAPA19 + MAPA20
+ MAPA21 + MAPA22 + MAPA23 + MAPA24 + MAPA25 + MAPA26 + MAPA27 + MAPA28
'


## models
mapa_mg <- equal_test(overall.model, mapa_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]), 
    "Overall", mapa_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]),
    "Random", mapa_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mapa_mg$random.equal$chi,
    fitmeasures(mapa_mg$random, "df"),
    mapa_mg$random.equal$popdelt,
    mapa_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mapa_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mapa_mg$nonrandom.equal$chi,
    fitmeasures(mapa_mg$nonrandom, "df"),
    mapa_mg$nonrandom.equal$popdelt,
    mapa_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mapa_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mapa_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mapa_mg$metric.equal$chi,
    abs(fitmeasures(mapa_mg$metric, "df") - fitmeasures(mapa_mg$configural, "df")),
    mapa_mg$metric.equal$popdelt,
    mapa_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mapa_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mapa_mg$scalar.equal$chi,
    abs(fitmeasures(mapa_mg$scalar, "df") - fitmeasures(mapa_mg$metric, "df")),
    mapa_mg$scalar.equal$popdelt,
    mapa_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mapa_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mapa_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mapa_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mapa_mg$residuals.equal$chi,
    abs(fitmeasures(mapa_mg$residuals, "df") - fitmeasures(mapa_mg$scalar, "df")),
    mapa_mg$residuals.equal$popdelt,
    mapa_mg$residuals.equal$pval)

```

```{r mg_meaning, include = F}
# Model Code
##Erin - there are two in the MG analyses.Rmd that say 'Meaning' as the chunk headers. not sure what this means
```

```{r mg_mlm, include = F}
# Model Code
overall.model = '
Exciting =~ MLM1 + MLM2 + MLM3 + MLM4 + MLM5 
Accomplished =~ MLM6 + MLM7 + MLM8 + MLM9 + MLM10
Principled =~ MLM11 + MLM12 + MLM13 + MLM14 + MLM15
Purposeful =~ MLM16 + MLM17 + MLM18 + MLM19  
Valued =~ MLM20 + MLM21 + MLM22 + MLM23
'


## models
mlm_mg <- equal_test(overall.model, mlm_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]), 
    "Overall", mlm_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]),
    "Random", mlm_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlm_mg$random.equal$chi,
    fitmeasures(mlm_mg$random, "df"),
    mlm_mg$random.equal$popdelt,
    mlm_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mlm_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlm_mg$nonrandom.equal$chi,
    fitmeasures(mlm_mg$nonrandom, "df"),
    mlm_mg$nonrandom.equal$popdelt,
    mlm_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mlm_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mlm_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlm_mg$metric.equal$chi,
    abs(fitmeasures(mlm_mg$metric, "df") - fitmeasures(mlm_mg$configural, "df")),
    mlm_mg$metric.equal$popdelt,
    mlm_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mlm_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlm_mg$scalar.equal$chi,
    abs(fitmeasures(mlm_mg$scalar, "df") - fitmeasures(mlm_mg$metric, "df")),
    mlm_mg$scalar.equal$popdelt,
    mlm_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlm_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mlm_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlm_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlm_mg$residuals.equal$chi,
    abs(fitmeasures(mlm_mg$residuals, "df") - fitmeasures(mlm_mg$scalar, "df")),
    mlm_mg$residuals.equal$popdelt,
    mlm_mg$residuals.equal$pval)

```

```{r mg_mils, include = F}
# Model Code
overall.model = '
harmony =~ MILS17 + MILS16 + MILS20 + MILS15
lifeperspective =~ MILS1 + MILS3 + MILS6 + MILS7 + MILS9 + MILS11 + MILS13
confusion =~ MILS2 + MILS5 + MILS4 + MILS8 + MILS10 + MILS12 + MILS14
spirit =~ MILS18 + MILS19
'



## models
mils_mg <- equal_test(overall.model, mils_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]), 
    "Overall", mils_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]),
    "Random", mils_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mils_mg$random.equal$chi,
    fitmeasures(mils_mg$random, "df"),
    mils_mg$random.equal$popdelt,
    mils_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mils_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mils_mg$nonrandom.equal$chi,
    fitmeasures(mils_mg$nonrandom, "df"),
    mils_mg$nonrandom.equal$popdelt,
    mils_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mils_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mils_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mils_mg$metric.equal$chi,
    abs(fitmeasures(mils_mg$metric, "df") - fitmeasures(mils_mg$configural, "df")),
    mils_mg$metric.equal$popdelt,
    mils_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mils_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mils_mg$scalar.equal$chi,
    abs(fitmeasures(mils_mg$scalar, "df") - fitmeasures(mils_mg$metric, "df")),
    mils_mg$scalar.equal$popdelt,
    mils_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mils_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mils_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mils_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mils_mg$residuals.equal$chi,
    abs(fitmeasures(mils_mg$residuals, "df") - fitmeasures(mils_mg$scalar, "df")),
    mils_mg$residuals.equal$popdelt,
    mils_mg$residuals.equal$pval)

```

```{r mg_mil kernes???, include = F}

##issue with this one in DS stuff as well, looks like repeat of MLQ? We have one for Kernes and one for Steger. Need to figure out which one needs to get added 

```

```{r mg_mlq, include = F}
# Model Code
overall.model = '
Presence =~ MLQ1 + MLQ4 + MLQ5 + MLQ6 + MLQ9
Search =~ MLQ2 + MLQ3 + MLQ7 + MLQ8 + MLQ10
'

## models
mlq_mg <- equal_test(overall.model, mlq_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]), 
    "Overall", mlq_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]),
    "Random", mlq_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlq_mg$random.equal$chi,
    fitmeasures(mlq_mg$random, "df"),
    mlq_mg$random.equal$popdelt,
    mlq_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mlq_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlq_mg$nonrandom.equal$chi,
    fitmeasures(mlq_mg$nonrandom, "df"),
    mlq_mg$nonrandom.equal$popdelt,
    mlq_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mlq_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mlq_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlq_mg$metric.equal$chi,
    abs(fitmeasures(mlq_mg$metric, "df") - fitmeasures(mlq_mg$configural, "df")),
    mlq_mg$metric.equal$popdelt,
    mlq_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mlq_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlq_mg$scalar.equal$chi,
    abs(fitmeasures(mlq_mg$scalar, "df") - fitmeasures(mlq_mg$metric, "df")),
    mlq_mg$scalar.equal$popdelt,
    mlq_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlq_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mlq_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlq_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlq_mg$residuals.equal$chi,
    abs(fitmeasures(mlq_mg$residuals, "df") - fitmeasures(mlq_mg$scalar, "df")),
    mlq_mg$residuals.equal$popdelt,
    mlq_mg$residuals.equal$pval)

```


```{r mg_mlt, include = F}
# Model Code
overall.model = '
MLT =~ MLT1 + MLT2 + MLT3 + MLT4
'

## models
mlt_mg <- equal_test(overall.model, mlt_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]), 
    "Overall", mlt_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]),
    "Random", mlt_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlt_mg$random.equal$chi,
    fitmeasures(mlt_mg$random, "df"),
    mlt_mg$random.equal$popdelt,
    mlt_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mlt_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlt_mg$nonrandom.equal$chi,
    fitmeasures(mlt_mg$nonrandom, "df"),
    mlt_mg$nonrandom.equal$popdelt,
    mlt_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mlt_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mlt_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlt_mg$metric.equal$chi,
    abs(fitmeasures(mlt_mg$metric, "df") - fitmeasures(mlt_mg$configural, "df")),
    mlt_mg$metric.equal$popdelt,
    mlt_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mlt_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlt_mg$scalar.equal$chi,
    abs(fitmeasures(mlt_mg$scalar, "df") - fitmeasures(mlt_mg$metric, "df")),
    mlt_mg$scalar.equal$popdelt,
    mlt_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mlt_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mlt_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mlt_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mlt_mg$residuals.equal$chi,
    abs(fitmeasures(mlt_mg$residuals, "df") - fitmeasures(mlt_mg$scalar, "df")),
    mlt_mg$residuals.equal$popdelt,
    mlt_mg$residuals.equal$pval)

```


```{r mg_milw, include = F}
# Model Code
##this is the werner one 
overall.model = 'ML =~ ML1 + ML2 + ML3 + ML4 + ML5 + ML6 + ML7 + ML8 +
      ML9 + ML10 + ML11 + ML12 + ML13 + ML14
'
## models
ml_mg <- equal_test(overall.model, ml_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]), 
    "Overall", ml_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]),
    "Random", ml_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ml_mg$random.equal$chi,
    fitmeasures(ml_mg$random, "df"),
    ml_mg$random.equal$popdelt,
    ml_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]),
    "NonRandom", ml_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ml_mg$nonrandom.equal$chi,
    fitmeasures(ml_mg$nonrandom, "df"),
    ml_mg$nonrandom.equal$popdelt,
    ml_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(ml_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(ml_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ml_mg$metric.equal$chi,
    abs(fitmeasures(ml_mg$metric, "df") - fitmeasures(ml_mg$configural, "df")),
    ml_mg$metric.equal$popdelt,
    ml_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(ml_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ml_mg$scalar.equal$chi,
    abs(fitmeasures(ml_mg$scalar, "df") - fitmeasures(ml_mg$metric, "df")),
    ml_mg$scalar.equal$popdelt,
    ml_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(ml_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(ml_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(ml_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    ml_mg$residuals.equal$chi,
    abs(fitmeasures(ml_mg$residuals, "df") - fitmeasures(ml_mg$scalar, "df")),
    ml_mg$residuals.equal$popdelt,
    ml_mg$residuals.equal$pval)

```


```{r mg_mili, include = F}
# Model Code
overallmodel = '
MILI =~ MILI1 + MILI2 + MILI3 + MILI4 + MILI5 + MILI6 + MILI7 + MILI8 + MILI9
'

## models
mili_mg <- equal_test(overall.model, mili_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]), 
    "Overall", mili_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]),
    "Random", mili_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mili_mg$random.equal$chi,
    fitmeasures(mili_mg$random, "df"),
    mili_mg$random.equal$popdelt,
    mili_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mili_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mili_mg$nonrandom.equal$chi,
    fitmeasures(mili_mg$nonrandom, "df"),
    mili_mg$nonrandom.equal$popdelt,
    mili_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mili_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mili_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mili_mg$metric.equal$chi,
    abs(fitmeasures(mili_mg$metric, "df") - fitmeasures(mili_mg$configural, "df")),
    mili_mg$metric.equal$popdelt,
    mili_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mili_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mili_mg$scalar.equal$chi,
    abs(fitmeasures(mili_mg$scalar, "df") - fitmeasures(mili_mg$metric, "df")),
    mili_mg$scalar.equal$popdelt,
    mili_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mili_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mili_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mili_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mili_mg$residuals.equal$chi,
    abs(fitmeasures(mili_mg$residuals, "df") - fitmeasures(mili_mg$scalar, "df")),
    mili_mg$residuals.equal$popdelt,
    mili_mg$residuals.equal$pval)

```

```{r mg_mms, include = F}
# Model Code
overallmodel = '
MMS =~ MMS1 + MMS2 + MMS3 + MMS4 + MMS5 + MMS6 + MMS7
'

## models
mms_mg <- equal_test(overall.model, mms_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]), 
    "Overall", mms_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]),
    "Random", mms_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mms_mg$random.equal$chi,
    fitmeasures(mms_mg$random, "df"),
    mms_mg$random.equal$popdelt,
    mms_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mms_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mms_mg$nonrandom.equal$chi,
    fitmeasures(mms_mg$nonrandom, "df"),
    mms_mg$nonrandom.equal$popdelt,
    mms_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mms_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mms_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mms_mg$metric.equal$chi,
    abs(fitmeasures(mms_mg$metric, "df") - fitmeasures(mms_mg$configural, "df")),
    mms_mg$metric.equal$popdelt,
    mms_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mms_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mms_mg$scalar.equal$chi,
    abs(fitmeasures(mms_mg$scalar, "df") - fitmeasures(mms_mg$metric, "df")),
    mms_mg$scalar.equal$popdelt,
    mms_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mms_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mms_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mms_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mms_mg$residuals.equal$chi,
    abs(fitmeasures(mms_mg$residuals, "df") - fitmeasures(mms_mg$scalar, "df")),
    mms_mg$residuals.equal$popdelt,
    mms_mg$residuals.equal$pval)

```

```{r mg_mm, include = F}
# Model Code
overall.model = '
Coherence =~ MMM1 + MMM2 + MMM3 + MMM4 
Integration =~ MMM5 + MMM6 +MMM7 + MMM8  
HLAIdentification =~ MMM9 + MMM10 + MMM11 + MMM12   
SunseofPurpose =~ MMM13 + MMM14 + MMM15 + MMM16    
'

## models
mm_mg <- equal_test(overall.model, mm_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]), 
    "Overall", mm_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]),
    "Random", mm_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mm_mg$random.equal$chi,
    fitmeasures(mm_mg$random, "df"),
    mm_mg$random.equal$popdelt,
    mm_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]),
    "NonRandom", mm_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mm_mg$nonrandom.equal$chi,
    fitmeasures(mm_mg$nonrandom, "df"),
    mm_mg$nonrandom.equal$popdelt,
    mm_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(mm_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(mm_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mm_mg$metric.equal$chi,
    abs(fitmeasures(mm_mg$metric, "df") - fitmeasures(mm_mg$configural, "df")),
    mm_mg$metric.equal$popdelt,
    mm_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(mm_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mm_mg$scalar.equal$chi,
    abs(fitmeasures(mm_mg$scalar, "df") - fitmeasures(mm_mg$metric, "df")),
    mm_mg$scalar.equal$popdelt,
    mm_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(mm_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(mm_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(mm_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    mm_mg$residuals.equal$chi,
    abs(fitmeasures(mm_mg$residuals, "df") - fitmeasures(mm_mg$scalar, "df")),
    mm_mg$residuals.equal$popdelt,
    mm_mg$residuals.equal$pval)

```

```{r mg_nom, include = F}
# Model Code
overall.model = '
NoMean =~ NOM1 + NOM2 + NOM3 + NOM4 + NOM5 + NOM6 + NOM7 + NOM8 + NOM9 + NOM10 + NOM11 + NOM12 + NOM13 + NOM14
'

## models
nom_mg <- equal_test(overall.model, nom_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]), 
    "Overall", nom_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]),
    "Random", nom_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    nom_mg$random.equal$chi,
    fitmeasures(nom_mg$random, "df"),
    nom_mg$random.equal$popdelt,
    nom_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]),
    "NonRandom", nom_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    nom_mg$nonrandom.equal$chi,
    fitmeasures(nom_mg$nonrandom, "df"),
    nom_mg$nonrandom.equal$popdelt,
    nom_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(nom_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(nom_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    nom_mg$metric.equal$chi,
    abs(fitmeasures(nom_mg$metric, "df") - fitmeasures(nom_mg$configural, "df")),
    nom_mg$metric.equal$popdelt,
    nom_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(nom_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    nom_mg$scalar.equal$chi,
    abs(fitmeasures(nom_mg$scalar, "df") - fitmeasures(nom_mg$metric, "df")),
    nom_mg$scalar.equal$popdelt,
    nom_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(nom_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(nom_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(nom_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    nom_mg$residuals.equal$chi,
    abs(fitmeasures(nom_mg$residuals, "df") - fitmeasures(nom_mg$scalar, "df")),
    nom_mg$residuals.equal$popdelt,
    nom_mg$residuals.equal$pval)

```

```{r mg_oth, include = F}
# Model Code
overall.model = '
MN =~ OHS2 + OHS5 + OHS11 + OHS12 + OHS14 + OHS17 
EG =~ OHS3 + OHS8 + OHS13 + OHS15 + OHS16 + OHS18
PL =~ OHS1 + OHS4 + OHS6 + OHS7 + OHS9 + OHS10
'

## models
oth_mg <- equal_test(overall.model, oth_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]), 
    "Overall", oth_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]),
    "Random", oth_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    oth_mg$random.equal$chi,
    fitmeasures(oth_mg$random, "df"),
    oth_mg$random.equal$popdelt,
    oth_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]),
    "NonRandom", oth_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    oth_mg$nonrandom.equal$chi,
    fitmeasures(oth_mg$nonrandom, "df"),
    oth_mg$nonrandom.equal$popdelt,
    oth_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(oth_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(oth_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    oth_mg$metric.equal$chi,
    abs(fitmeasures(oth_mg$metric, "df") - fitmeasures(oth_mg$configural, "df")),
    oth_mg$metric.equal$popdelt,
    oth_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(oth_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    oth_mg$scalar.equal$chi,
    abs(fitmeasures(oth_mg$scalar, "df") - fitmeasures(oth_mg$metric, "df")),
    oth_mg$scalar.equal$popdelt,
    oth_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(oth_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(oth_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(oth_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    oth_mg$residuals.equal$chi,
    abs(fitmeasures(oth_mg$residuals, "df") - fitmeasures(oth_mg$scalar, "df")),
    oth_mg$residuals.equal$popdelt,
    oth_mg$residuals.equal$pval)

```

```{r mg_pvs, include = F}
# Model Code
overall.model = '
PVS =~
PVS1 + PVS2 + PVS3 + PVS4 + PVS5 + PVS6 + PVS7 + PVS8 +
PVS9 + PVS10 + PVS11 + PVS12 + PVS13 + PVS14 + PVS15 +
PVS16 + PVS17 + PVS18
'

## models
pvs_mg <- equal_test(overall.model, pvs_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]), 
    "Overall", pvs_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]),
    "Random", pvs_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pvs_mg$random.equal$chi,
    fitmeasures(pvs_mg$random, "df"),
    pvs_mg$random.equal$popdelt,
    pvs_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pvs_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pvs_mg$nonrandom.equal$chi,
    fitmeasures(pvs_mg$nonrandom, "df"),
    pvs_mg$nonrandom.equal$popdelt,
    pvs_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pvs_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pvs_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pvs_mg$metric.equal$chi,
    abs(fitmeasures(pvs_mg$metric, "df") - fitmeasures(pvs_mg$configural, "df")),
    pvs_mg$metric.equal$popdelt,
    pvs_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pvs_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pvs_mg$scalar.equal$chi,
    abs(fitmeasures(pvs_mg$scalar, "df") - fitmeasures(pvs_mg$metric, "df")),
    pvs_mg$scalar.equal$popdelt,
    pvs_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pvs_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pvs_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pvs_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pvs_mg$residuals.equal$chi,
    abs(fitmeasures(pvs_mg$residuals, "df") - fitmeasures(pvs_mg$scalar, "df")),
    pvs_mg$residuals.equal$popdelt,
    pvs_mg$residuals.equal$pval)

```

```{r mg_pil, include = F}
# Model Code
overall.model = 'Purpose =~
PIL1 + PIL2 + PIL3 + PIL4 + PIL5 + PIL6 + PIL7 + PIL8 + PIL9
+ PIL10 + PIL11 +PIL12 + PIL13 + PIL14 + PIL15 + PIL16 + PIL17 + PIL18 + PIL19 + PIL20
'

## models
pil_mg <- equal_test(overall.model, pil_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]), 
    "Overall", pil_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]),
    "Random", pil_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pil_mg$random.equal$chi,
    fitmeasures(pil_mg$random, "df"),
    pil_mg$random.equal$popdelt,
    pil_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pil_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pil_mg$nonrandom.equal$chi,
    fitmeasures(pil_mg$nonrandom, "df"),
    pil_mg$nonrandom.equal$popdelt,
    pil_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pil_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pil_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pil_mg$metric.equal$chi,
    abs(fitmeasures(pil_mg$metric, "df") - fitmeasures(pil_mg$configural, "df")),
    pil_mg$metric.equal$popdelt,
    pil_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pil_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pil_mg$scalar.equal$chi,
    abs(fitmeasures(pil_mg$scalar, "df") - fitmeasures(pil_mg$metric, "df")),
    pil_mg$scalar.equal$popdelt,
    pil_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pil_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pil_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pil_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pil_mg$residuals.equal$chi,
    abs(fitmeasures(pil_mg$residuals, "df") - fitmeasures(pil_mg$scalar, "df")),
    pil_mg$residuals.equal$popdelt,
    pil_mg$residuals.equal$pval)

```

```{r mg_pilsf, include = F}
# Model Code
overall.model = '
PIL =~ PILSF1 + PILSF2 + PILSF3 + PILSF4 + PILSF5
'

## models
pilsf_mg <- equal_test(overall.model, pilsf_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]), 
    "Overall", pilsf_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]),
    "Random", pilsf_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pilsf_mg$random.equal$chi,
    fitmeasures(pilsf_mg$random, "df"),
    pilsf_mg$random.equal$popdelt,
    pilsf_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pilsf_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pilsf_mg$nonrandom.equal$chi,
    fitmeasures(pilsf_mg$nonrandom, "df"),
    pilsf_mg$nonrandom.equal$popdelt,
    pilsf_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pilsf_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pilsf_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pilsf_mg$metric.equal$chi,
    abs(fitmeasures(pilsf_mg$metric, "df") - fitmeasures(pilsf_mg$configural, "df")),
    pilsf_mg$metric.equal$popdelt,
    pilsf_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pilsf_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pilsf_mg$scalar.equal$chi,
    abs(fitmeasures(pilsf_mg$scalar, "df") - fitmeasures(pilsf_mg$metric, "df")),
    pilsf_mg$scalar.equal$popdelt,
    pilsf_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pilsf_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pilsf_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pilsf_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pilsf_mg$residuals.equal$chi,
    abs(fitmeasures(pilsf_mg$residuals, "df") - fitmeasures(pilsf_mg$scalar, "df")),
    pilsf_mg$residuals.equal$popdelt,
    pilsf_mg$residuals.equal$pval)

```

```{r mg_pms, include = F}
# Model Code
overall.model = '
PMS =~ PPMS1 + PPMS2 + PPMS3 + PPMS4 + PPMS5 + PPMS6 + PPMS7 + PPMS8'

## models
pms_mg <- equal_test(overall.model, pms_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]), 
    "Overall", pms_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]),
    "Random", pms_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pms_mg$random.equal$chi,
    fitmeasures(pms_mg$random, "df"),
    pms_mg$random.equal$popdelt,
    pms_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pms_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pms_mg$nonrandom.equal$chi,
    fitmeasures(pms_mg$nonrandom, "df"),
    pms_mg$nonrandom.equal$popdelt,
    pms_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pms_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pms_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pms_mg$metric.equal$chi,
    abs(fitmeasures(pms_mg$metric, "df") - fitmeasures(pms_mg$configural, "df")),
    pms_mg$metric.equal$popdelt,
    pms_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pms_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pms_mg$scalar.equal$chi,
    abs(fitmeasures(pms_mg$scalar, "df") - fitmeasures(pms_mg$metric, "df")),
    pms_mg$scalar.equal$popdelt,
    pms_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pms_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pms_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pms_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pms_mg$residuals.equal$chi,
    abs(fitmeasures(pms_mg$residuals, "df") - fitmeasures(pms_mg$scalar, "df")),
    pms_mg$residuals.equal$popdelt,
    pms_mg$residuals.equal$pval)

```

```{r mg_pvsh, include = F}
# There were some issues with this one in the DS code, too. 

```

```{r mg_qe, include = F}
# Model Code
overall.model = '
QEWB =~ QEWB1 + QEWB2 + QEWB3 + QEWB4 + QEWB5 + QEWB6 + QEWB7 + QEWB8 + QEWB9 + QEWB10 + QEWB11 + QEWB12 + QEWB13 + QEWB14 + QEWB15 + QEWB16 + QEWB17 + QEWB18 + QEWB19 + QEWB20 + QEWB21
'

## models
qe_mg <- equal_test(overall.model, qe_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]), 
    "Overall", qe_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]),
    "Random", qe_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    qe_mg$random.equal$chi,
    fitmeasures(qe_mg$random, "df"),
    qe_mg$random.equal$popdelt,
    qe_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]),
    "NonRandom", qe_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    qe_mg$nonrandom.equal$chi,
    fitmeasures(qe_mg$nonrandom, "df"),
    qe_mg$nonrandom.equal$popdelt,
    qe_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(qe_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(qe_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    qe_mg$metric.equal$chi,
    abs(fitmeasures(qe_mg$metric, "df") - fitmeasures(qe_mg$configural, "df")),
    qe_mg$metric.equal$popdelt,
    qe_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(qe_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    qe_mg$scalar.equal$chi,
    abs(fitmeasures(qe_mg$scalar, "df") - fitmeasures(qe_mg$metric, "df")),
    qe_mg$scalar.equal$popdelt,
    qe_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(qe_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(qe_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(qe_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    qe_mg$residuals.equal$chi,
    abs(fitmeasures(qe_mg$residuals, "df") - fitmeasures(qe_mg$scalar, "df")),
    qe_mg$residuals.equal$popdelt,
    qe_mg$residuals.equal$pval)

```


```{r mg_rs14, include = F}
# Model Code
overall.model = '
ResScale =~
RS1 + RS2 + RS3 + RS4 + RS5 + 
RS6 + RS7 + RS8 + RS9 + RS10 +
RS11 + RS12 + RS13 + RS14
'
## models
rs14_mg <- equal_test(overall.model, rs14_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]), 
    "Overall", rs14_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]),
    "Random", rs14_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rs14_mg$random.equal$chi,
    fitmeasures(rs14_mg$random, "df"),
    rs14_mg$random.equal$popdelt,
    rs14_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]),
    "NonRandom", rs14_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rs14_mg$nonrandom.equal$chi,
    fitmeasures(rs14_mg$nonrandom, "df"),
    rs14_mg$nonrandom.equal$popdelt,
    rs14_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(rs14_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(rs14_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rs14_mg$metric.equal$chi,
    abs(fitmeasures(rs14_mg$metric, "df") - fitmeasures(rs14_mg$configural, "df")),
    rs14_mg$metric.equal$popdelt,
    rs14_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(rs14_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rs14_mg$scalar.equal$chi,
    abs(fitmeasures(rs14_mg$scalar, "df") - fitmeasures(rs14_mg$metric, "df")),
    rs14_mg$scalar.equal$popdelt,
    rs14_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(rs14_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(rs14_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(rs14_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rs14_mg$residuals.equal$chi,
    abs(fitmeasures(rs14_mg$residuals, "df") - fitmeasures(rs14_mg$scalar, "df")),
    rs14_mg$residuals.equal$popdelt,
    rs14_mg$residuals.equal$pval)

```


```{r mg_swl, include = F}
# Model Code
overall.model = '
SWLS =~ SWLS1 + SWLS2 + SWLS3 + SWLS4 + SWLS5
'
## models
swl_mg <- equal_test(overall.model, swl_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]), 
    "Overall", swl_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]),
    "Random", swl_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    swl_mg$random.equal$chi,
    fitmeasures(swl_mg$random, "df"),
    swl_mg$random.equal$popdelt,
    swl_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]),
    "NonRandom", swl_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    swl_mg$nonrandom.equal$chi,
    fitmeasures(swl_mg$nonrandom, "df"),
    swl_mg$nonrandom.equal$popdelt,
    swl_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(swl_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(swl_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    swl_mg$metric.equal$chi,
    abs(fitmeasures(swl_mg$metric, "df") - fitmeasures(swl_mg$configural, "df")),
    swl_mg$metric.equal$popdelt,
    swl_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(swl_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    swl_mg$scalar.equal$chi,
    abs(fitmeasures(swl_mg$scalar, "df") - fitmeasures(swl_mg$metric, "df")),
    swl_mg$scalar.equal$popdelt,
    swl_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(swl_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(swl_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(swl_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    swl_mg$residuals.equal$chi,
    abs(fitmeasures(swl_mg$residuals, "df") - fitmeasures(swl_mg$scalar, "df")),
    swl_mg$residuals.equal$popdelt,
    swl_mg$residuals.equal$pval)

```


```{r mg_song, include = F}
# Model Code
overall.model = '
VA =~ SONG3 + SONG4 + SONG8 + SONG9 + SONG11 + SONG12 + SONG13 + SONG14 + SONG17 + SONG19
WM =~ SONG1 + SONG6 + SONG7 + SONG10 + SONG15 + SONG18 + SONG20
'
## models
song_mg <- equal_test(overall.model, song_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]), 
    "Overall", song_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]),
    "Random", song_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    song_mg$random.equal$chi,
    fitmeasures(song_mg$random, "df"),
    song_mg$random.equal$popdelt,
    song_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]),
    "NonRandom", song_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    song_mg$nonrandom.equal$chi,
    fitmeasures(song_mg$nonrandom, "df"),
    song_mg$nonrandom.equal$popdelt,
    song_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(song_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(song_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    song_mg$metric.equal$chi,
    abs(fitmeasures(song_mg$metric, "df") - fitmeasures(song_mg$configural, "df")),
    song_mg$metric.equal$popdelt,
    song_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(song_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    song_mg$scalar.equal$chi,
    abs(fitmeasures(song_mg$scalar, "df") - fitmeasures(song_mg$metric, "df")),
    song_mg$scalar.equal$popdelt,
    song_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(song_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(song_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(song_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    song_mg$residuals.equal$chi,
    abs(fitmeasures(song_mg$residuals, "df") - fitmeasures(song_mg$scalar, "df")),
    song_mg$residuals.equal$popdelt,
    song_mg$residuals.equal$pval)

```


```{r mg_soc, include = F}
# Model Code
##problem here - 30 items show up in data, but scale is 29 item. leaving for now -Jeff 

library(lavaan)
##data sets
overallmodel = '
Comprehensibility =~
Managability =~
Meaningfulness =~
'

```

```{r mg_som, include = F}
# Model Code
##this one needs to be resolved with the factor structure. I didn't screen it but am not sure what the structure is. - Jeff

```


```{r mg_sms, include = F}
# Model Code
overall.model = '
SMS =~
SMS1 + SMS2 + SMS3 + SMS4 + SMS5 + SMS6.5 + 
SMS8 + SMS9 + SMS10 + SMS11 + SMS12 + SMS13 + SMS14 +
SMS15 + SMS16
'

## models
sms_mg <- equal_test(overall.model, sms_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]), 
    "Overall", sms_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]),
    "Random", sms_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    sms_mg$random.equal$chi,
    fitmeasures(sms_mg$random, "df"),
    sms_mg$random.equal$popdelt,
    sms_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]),
    "NonRandom", sms_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    sms_mg$nonrandom.equal$chi,
    fitmeasures(sms_mg$nonrandom, "df"),
    sms_mg$nonrandom.equal$popdelt,
    sms_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(sms_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(sms_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    sms_mg$metric.equal$chi,
    abs(fitmeasures(sms_mg$metric, "df") - fitmeasures(sms_mg$configural, "df")),
    sms_mg$metric.equal$popdelt,
    sms_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(sms_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    sms_mg$scalar.equal$chi,
    abs(fitmeasures(sms_mg$scalar, "df") - fitmeasures(sms_mg$metric, "df")),
    sms_mg$scalar.equal$popdelt,
    sms_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(sms_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(sms_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(sms_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    sms_mg$residuals.equal$chi,
    abs(fitmeasures(sms_mg$residuals, "df") - fitmeasures(sms_mg$scalar, "df")),
    sms_mg$residuals.equal$popdelt,
    sms_mg$residuals.equal$pval)

```

```{r mg_stms, include = F}
# Model Code
overall.model = '
PH =~ STMS17 + STMS24 + STMS16 + STMS19 + STMS20 + STMS26 + STMS22 + STMS21 + STMS23 + STMS27 + STMS15 + STMS30 + STMS28 + STMS25 + STMS29 + STMS18 + STMS33 + STMS8 + STMS32
AH =~ STMS2 + STMS3 + STMS12 + STMS10 + STMS9 + STMS4 + STMS1 + STMS7 + STMS11 + STMS6 + STMS5 
NLE =~ STMS14 + STMS13 + STMS31
'


## models
stms_mg <- equal_test(overall.model, stms_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]), 
    "Overall", stms_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]),
    "Random", stms_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    stms_mg$random.equal$chi,
    fitmeasures(stms_mg$random, "df"),
    stms_mg$random.equal$popdelt,
    stms_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]),
    "NonRandom", stms_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    stms_mg$nonrandom.equal$chi,
    fitmeasures(stms_mg$nonrandom, "df"),
    stms_mg$nonrandom.equal$popdelt,
    stms_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(stms_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(stms_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    stms_mg$metric.equal$chi,
    abs(fitmeasures(stms_mg$metric, "df") - fitmeasures(stms_mg$configural, "df")),
    stms_mg$metric.equal$popdelt,
    stms_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(stms_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    stms_mg$scalar.equal$chi,
    abs(fitmeasures(stms_mg$scalar, "df") - fitmeasures(stms_mg$metric, "df")),
    stms_mg$scalar.equal$popdelt,
    stms_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(stms_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(stms_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(stms_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    stms_mg$residuals.equal$chi,
    abs(fitmeasures(stms_mg$residuals, "df") - fitmeasures(stms_mg$scalar, "df")),
    stms_mg$residuals.equal$popdelt,
    stms_mg$residuals.equal$pval)

```

```{r mg_vol, include = F}
# Model Code
overall.model = '
POS =~ VOL1 + VOL2 + VOL3 + VOL4 + VOL5 + VOL6 + VOL7 + VOL8 + VOL9 + VOL10 + VOL11 + VOL12 + VOL13
NEG =~ VOL14 + VOL15 + VOL16 + VOL17 + VOL18 + VOL19
'

## models
vol_mg <- equal_test(overall.model, vol_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]), 
    "Overall", vol_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]),
    "Random", vol_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    vol_mg$random.equal$chi,
    fitmeasures(vol_mg$random, "df"),
    vol_mg$random.equal$popdelt,
    vol_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]),
    "NonRandom", vol_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    vol_mg$nonrandom.equal$chi,
    fitmeasures(vol_mg$nonrandom, "df"),
    vol_mg$nonrandom.equal$popdelt,
    vol_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(vol_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(vol_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    vol_mg$metric.equal$chi,
    abs(fitmeasures(vol_mg$metric, "df") - fitmeasures(vol_mg$configural, "df")),
    vol_mg$metric.equal$popdelt,
    vol_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(vol_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    vol_mg$scalar.equal$chi,
    abs(fitmeasures(vol_mg$scalar, "df") - fitmeasures(vol_mg$metric, "df")),
    vol_mg$scalar.equal$popdelt,
    vol_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(vol_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(vol_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(vol_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    vol_mg$residuals.equal$chi,
    abs(fitmeasures(vol_mg$residuals, "df") - fitmeasures(vol_mg$scalar, "df")),
    vol_mg$residuals.equal$popdelt,
    vol_mg$residuals.equal$pval)

```

```{r mg_pws, include = F}
# Model Code
overall.model = '
AUT =~ PWS1 + PWS7 + PWS13 + PWS19 + PWS25 + PWS31 + PWS37
EM =~ PWS2 + PWS8 + PWS14 + PWS20 + PWS26 + PWS32 + PWS38
PG =~ PWS3 + PWS9 + PWS15 + PWS21 + PWS27 + PWS33 + PWS39 
PR =~ PWS4 + PWS10 + PWS16 + PWS22 + PWS28 + PWS34 + PWS40
PL =~ PWS5 + PWS11 + PWS17 + PWS23 + PWS29 + PWS35 + PWS41
SA =~ PWS6 + PWS12 + PWS18 + PWS24 + PWS30 + PWS36 + PWS42
'
## models
pws_mg <- equal_test(overall.model, pws_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]), 
    "Overall", pws_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Random", pws_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$random.equal$chi,
    fitmeasures(pws_mg$random, "df"),
    pws_mg$random.equal$popdelt,
    pws_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pws_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$nonrandom.equal$chi,
    fitmeasures(pws_mg$nonrandom, "df"),
    pws_mg$nonrandom.equal$popdelt,
    pws_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pws_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pws_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$metric.equal$chi,
    abs(fitmeasures(pws_mg$metric, "df") - fitmeasures(pws_mg$configural, "df")),
    pws_mg$metric.equal$popdelt,
    pws_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pws_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$scalar.equal$chi,
    abs(fitmeasures(pws_mg$scalar, "df") - fitmeasures(pws_mg$metric, "df")),
    pws_mg$scalar.equal$popdelt,
    pws_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pws_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$residuals.equal$chi,
    abs(fitmeasures(pws_mg$residuals, "df") - fitmeasures(pws_mg$scalar, "df")),
    pws_mg$residuals.equal$popdelt,
    pws_mg$residuals.equal$pval)

```


```{r mg_pws, include = F}
# Model Code
overall.model = '
AUT =~ PWS1 + PWS7 + PWS13 + PWS19 + PWS25 + PWS31 + PWS37
EM =~ PWS2 + PWS8 + PWS14 + PWS20 + PWS26 + PWS32 + PWS38
PG =~ PWS3 + PWS9 + PWS15 + PWS21 + PWS27 + PWS33 + PWS39 
PR =~ PWS4 + PWS10 + PWS16 + PWS22 + PWS28 + PWS34 + PWS40
PL =~ PWS5 + PWS11 + PWS17 + PWS23 + PWS29 + PWS35 + PWS41
SA =~ PWS6 + PWS12 + PWS18 + PWS24 + PWS30 + PWS36 + PWS42
'
## models
pws_mg <- equal_test(overall.model, pws_ds$fulldata, .10)

## Put that into the table 
summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]), 
    "Overall", pws_mg$overall@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$overall, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Random", pws_mg$random@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$random, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$random.equal$chi,
    fitmeasures(pws_mg$random, "df"),
    pws_mg$random.equal$popdelt,
    pws_mg$random.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "NonRandom", pws_mg$nonrandom@SampleStats@nobs[[1]], 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$nonrandom, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$nonrandom.equal$chi,
    fitmeasures(pws_mg$nonrandom, "df"),
    pws_mg$nonrandom.equal$popdelt,
    pws_mg$nonrandom.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Configural", sum(unlist(pws_mg$configural@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$configural, c("chisq", "df", "cfi", "rmsea", "srmr")),
    rep("NA", 4))

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]), 
    "Metric", sum(unlist(pws_mg$metric@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$metric, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$metric.equal$chi,
    abs(fitmeasures(pws_mg$metric, "df") - fitmeasures(pws_mg$configural, "df")),
    pws_mg$metric.equal$popdelt,
    pws_mg$metric.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Scalar", sum(unlist(pws_mg$scalar@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$scalar, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$scalar.equal$chi,
    abs(fitmeasures(pws_mg$scalar, "df") - fitmeasures(pws_mg$metric, "df")),
    pws_mg$scalar.equal$popdelt,
    pws_mg$scalar.equal$pval)

summary_mg[nrow(summary_mg)+1, ] <- 
  #scale name, model step, sample size
  c("BP", length(pws_mg$overall@Data@ov.names[[1]]),
    "Strict", sum(unlist(pws_mg$residuals@SampleStats@nobs)), 
    #chisq, df, cfi, rmsea, srmr
    fitmeasures(pws_mg$residuals, c("chisq", "df", "cfi", "rmsea", "srmr")),
    pws_mg$residuals.equal$chi,
    abs(fitmeasures(pws_mg$residuals, "df") - fitmeasures(pws_mg$scalar, "df")),
    pws_mg$residuals.equal$popdelt,
    pws_mg$residuals.equal$pval)

```
##Last 